### ISSUE TITLE
希望大佬能支持CMake构建系统，加入开源许可证

### ISSUE THREAD

**Issue by quqiOnfree** [sniper00/asio-kcp#3]
我看了一下这个仓库的源代码，觉得非常适合作为asio-kcp库来使用
希望作者顺便加入一下CMake构建系统配置和开源许可证，非常感谢！

**Comment by sniper00** [comment]
LICENSE 添加了, 库本身是header only的, 直接lnclude即可

**Comment by quqiOnfree** [comment]
Ok，非常感谢
